- hosts: workstation
  gather_facts: false
  tasks:
  - name: OpenStack servers
    os_server_facts:
     cloud: ospcloud
     server: frontend
    register: openstack_info
    tags:
      - osp.smoke

  - name: Check that a page returns a status 200 
    uri:
      url: "http://{{openstack_info.ansible_facts.openstack_servers[0].public_v4}}/"
      return_content: yes
    register: this
    failed_when: "'Ansible has done its job' not in this.content"
    tags:
      - osp.smoke
